INSERT INTO especialidades(cod_especialidade,des_especialidade) VALUES(
2200, 'Anestesiologia');

INSERT INTO especialidades(des_especialidade) VALUES
('Angiologia'),
('Cardiologia'),
('Cirurgia Cardiotorácica'),
('Cirurgia Geral'),
('Cirurgia Vascular'), 
('Dermatologia'),
('Endocrinologia'),
('Estomatologia'),
('Fisiatria'),
('Gastrenterologia'),
('Ginecologia'),
('Medicina Interna'),
('Medicina Intensiva'),
('Medicina Nuclear'),
('Nefrologia'), 
('Neurocirurgia'),
('Neurologia'),
('Neuropsicologia'),
('Neurorradiologia'),
('Obstetrícia'),
('Oftalmologia'),
('Oncologia'),
('Ortopedia'),
('Otorrinolaringologia'),
('Pediatria'),
('Pneumologia'),
('Psiquiatria'),
('Radiologia'),
('Reumatologia'),
('Urologia');